### ISSUE TITLE
First run after clean build errors out (missing sciota.db)

### ISSUE THREAD

**Issue by chronopoulos** [InterstitialTech/sciota-server#2]
The first time you build and run the server, like this:

```
cd server
cargo build
./target/debug/server
```

I get the following error:

```
initialdb
update1
error: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("near \"ON\": syntax error"))
```

However, this leaves sciota.db in the working directory, and subsequent attempts work fine.

**Comment by bburdette** [comment]
What's your sqlite version?  

```
[nix-shell:~/code/interstitial/sciota-server/server]$ sqlite3 
SQLite version 3.32.3 2020-06-18 14:00:33
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> 
```

I'm using an 'extended syntax' feature to [save the migration number](https://github.com/InterstitialTech/sciota-server/blob/5a3b30699708c63bffc4bf2d443171bf89753701/server/src/sqldata.rs#L125), this may not be available in older sqlite versions.

**Comment by chronopoulos** [comment]
```
$ sqlite3
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> 
```

but why would this error out the first time running, and then run fine for subsequent calls?

**Comment by bburdette** [comment]
I dunno; not sure what the failure mode is in sqlite 3.11.  It may insert the value into the table but still fail?  If that's the case then the next time it would run normally.  You can see that like this:

```
[nix-shell:~/code/interstitial/sciota-server/server]$ sqlite3 sciota.db 
SQLite version 3.32.3 2020-06-18 14:00:33
Enter ".help" for usage hints.
sqlite> select * from singlevalue;
migration_level|1
sqlite> 
```

Mine has migration_value of 1.  The idea with the migration_value is each time I apply an update to the database, I update the number.  So if I write an update to add a user_group table, and call that 2, but the database says '1', I know to apply the update.

At any rate, I can write some code to do what this does but without the fancy syntax.  You just have to write 3 sql commands instead of 1.

**Comment by bburdette** [comment]
K I maybe fixed this with PR 3:  https://github.com/InterstitialTech/sciota-server/pull/3.  Let me know if it works!

**Comment by chronopoulos** [comment]
yea, that worked! thanks!
